credentials:
  usernames:
    operation:
      email: operation@catalyst.id
      name: Operation Analyst
      password: $2a$04$YscOfRYdvdiZ02.1xzN42.zX8dvt5K6kWO/VtBFElBelxIeFOQ7g6
    finance:
      email: finance@catalyst.id
      name: Finance Analyst
      password: $2b$12$jnFBNelsRN9lYypXB.q02OlAsN7VxOOeEwAGBL7swA7ri80hB2CQK
cookie:
  expiry_days: 7
  key: rfmproductapps
  name: rfmproductapps_cookie_name
preauthorized:
  emails:
  - asdamgrimson@gmail.com